version: '3'
services:
  toady_app:
    container_name: toady_app
    build: toadyapp/.
    ports: 
      - "80:80"
    links:
      - toady_rest
  toady_rest:
    container_name: toady_rest
    build: toadyrest/.
    command: npm run test
    restart: on-failure
    depends_on:
      - toady_db
    links:
      - toady_db
    ports:
      - "8080:8080"
  toady_db:
    image: mariadb:10.5.8
    container_name: toady_db
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: toady
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: